name: Deploy Javadoc

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository files
          uses: actions/checkout@v3
        
        - name: Set up Java
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '8'
            
        - name: Build project
          run: |
            chmod +x ./run.sh
            printf '\ntest-login\n11111\npassword\n' |./run.sh build
          shell: bash
        
        - name: Generate documentation
          run: |
            chmod +x ./run.sh
            ./run.sh doc
            mv doc/ docs/
          shell: bash
        
        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./docs
